<!DOCTYPE html
	PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en-US" xml:lang="en-US">
<head>
<title>EasyChair Login Page for RMIT&#39;09</title>
<script>if (top != self) top.location.href=location.href;</script><link type="text/css" rel="StyleSheet" href="/css/ad.css?version=489" /><link type="text/css" rel="StyleSheet" href="/css/cool.css?version=489" /><link type="image/jpeg" rel="icon" href="/images/chairEC.jpg" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
</head>
<body>
<div id='content' class='nomenu'><script src="/js/easy.js?version=489"> </script><script src="signin.js?version=489"> </script><noscript><h1 class="red">EasyChair Requires JavaScript!</h1><p class="warning">You can only use EasyChair with a browser that
              supports JavaScript. Your browser either does not
              support JavaScript or it has JavaScript support disabled.
              Please upgrade your browser or enable Javascript support.</p></noscript><table cellspacing="0" style="border-collapse:collapse;padding:0px;border:0px" cellpadding="0"><tr><td colspan="3" style="vertical-align:top"><div style="height:26px;padding:0px 0px 0px 5px;margin:0px 0px 0px 5px;"><h2 id="title">EasyChair Login Page for RMIT'09</h2></div></td></tr><tr><td style="margin-top:0px;padding-top:0px;vertical-align:top"><form onsubmit="return login();" action="verify.cgi" style="margin:10px 0px 5px 0px" method="post"><table style="margin-top:0px;padding-top:0px" class="formtable1"><tr><td colspan="2" style="padding-bottom:5pt">Use your EasyChair account to sign in.</td></tr><tr><td class="right">User name:</td><td><input value="" name="name" type="text" id="name" size="30"/></td></tr><tr><td class="right">Password:</td><td><input name="password" type="password" id="password"/></td></tr><tr><td colspan="2"><input value="Sign in" name="Sign in" type="submit"/></td></tr><tr><td colspan="2"><hr/></td></tr><tr><td colspan="2" style="padding-bottom:5pt">If you have no EasyChair account, <a href="https://www.easychair.org/account/signup.cgi?conf=rmit09">sign up for an account</a></td></tr><tr><td colspan="2" style="padding-bottom:5pt">If you have problems to sign in <a href="https://www.easychair.org/account/problem.cgi?conf=rmit09">then click this link</a></td></tr></table><input value="rmit09" name="conf" type="hidden"/></form></td><td style="vertical-align:top"><a href="https://www.easychair.org/"><img src="/images/logoEC.gif" style="border:0px;padding:15pt 5pt 5pt 15pt"/></a></td><td style="vertical-align:top"><div class="adhead1"><a href="signin_ad.cgi?aid=1;cid=12740">The Turing Centenary Conference</a></div><div class="ad1"><div style="overflow:hidden"><a href="signin_ad.cgi?aid=1;cid=12740">www.turing100.manchester.ac.uk</a></div><div class="adcontent1">10 Turing Award winners and Garry Kasparov as invited speakers. Manchester, June 22-25, 2012</div></div><div class="adhead2"><a href="signin_ad.cgi?aid=3;cid=12740"> Manchester Centre for Doctoral Training</a></div><div class="ad2"><div style="overflow:hidden"><a href="signin_ad.cgi?aid=3;cid=12740">cdt.cs.manchester.ac.uk</a></div><div class="adcontent2">Fully funded studentships available for PhD study in Computer Science at the University of Manchester. Apply now for entry in September 2012.</div></div></td></tr></table></div>
</body>
</html>